[global]
# Disable caching to prevent cache-related issues
developmentMode = false

[server]
# Server configuration
port = 8501
headless = true
maxUploadSize = 200

[logger]
# Logging configuration
level = "info"
messageFormat = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[browser]
# Disable automatic browser opening
gatherUsageStats = false

[theme]
# Default theme
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

